# Generated by Django 4.2.7 on 2023-11-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_owner',
            field=models.CharField(default='Anonymous client', max_length=50),
        ),
    ]
