# Generated by Django 4.2.7 on 2023-11-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_order_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertoproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
