# Generated by Django 4.2.7 on 2023-11-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ordertoproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_owner',
            new_name='owner',
        ),
    ]
